[toolchain]
anchor_version = "0.26.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
crypto_fund_me = "8tPzm9ZtpPURBFGNXzFGJAPe2Q7JFMRu9YtEQTywCE2b"

[programs.devnet]
crypto_fund_me = "8tPzm9ZtpPURBFGNXzFGJAPe2Q7JFMRu9YtEQTywCE2b"

[programs.mainnet]
crypto_fund_me = "8tPzm9ZtpPURBFGNXzFGJAPe2Q7JFMRu9YtEQTywCE2b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 